### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by scoid** [MuzSumer/windvolt#1]
Small typo in 
 
 windvolt/fastlane/metadata/android/de/short_description.txt 
 
 Strategische Nutzung Ernuerbarer Energie
 
 should be:
 
 Strategische Nutzung erneuerbarer Energie

**Comment by MuzSumer** [comment]
contained in next release

Stephan Schildberg ***@***.***> schrieb am Do., 25. März
2021, 10:11:
